x-logstash-common: &logstash-common
  image: logstash/logstash:${VERSION}
  restart: unless-stopped
  expose:
    - "5044"
  environment:
    - ELASTICHOST=${ELASTICHOST}

services:
  logstash-01:
    <<: *logstash-common
    hostname: logstash-01
    container_name: logstash-01
    ports:
      - "${LOGSTASH01_OUTBOUND_PORT}:5044"
    volumes:
      - logstash-data-01:/usr/share/logstash/data
      - ./configs/pipeline:/usr/share/logstash/pipeline
      - ./configs/settings:/usr/share/logstash/config

  logstash-02:
    <<: *logstash-common
    hostname: logstash-02
    container_name: logstash-02
    ports:
      - "${LOGSTASH02_OUTBOUND_PORT}:5044"
    volumes:
      - logstash-data-02:/usr/share/logstash/data
      - ./configs/pipeline:/usr/share/logstash/pipeline
      - ./configs/settings:/usr/share/logstash/config

volumes:
  logstash-data-01:
    name: logstash-data-01
  logstash-data-02:
    name: logstash-data-02
